# -*- mode: ruby -*-

VAGRANTFILE_API_VERSION = "2"

Vagrant.require_version ">= 1.6.3"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  
  config.vm.box = "yungsang/boot2docker"
  config.vm.box_url = "https://vagrantcloud.com/yungsang/boxes/boot2docker/versions/26/providers/virtualbox.box"
  
  config.vm.synced_folder "../../", "/home/docker/pipeline-it"
  
  config.vm.network :forwarded_port, guest: 8081, host: 8081
  
  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "1024"]
  end
  
  config.vm.provision "docker" do |d|
    d.build_image "/home/docker/pipeline-it/nexus", args: "-t daisy/nexus"
    d.build_image "/home/docker/pipeline-it/reprepro", args: "-t daisy/reprepro"
    d.build_image "/home/docker/pipeline-it/platform/debian", args: "-t daisy/debian"
  end
  
  config.vm.provision "shell", run: "always", inline: "docker rm nexus reprepro || true"
  
  config.vm.provision "docker", run: "always" do |d|
    d.run "daisy/nexus", args: "-p 8081:8081 --name nexus", daemonize: true
    d.run "daisy/reprepro", args: "--link nexus:nexus --name reprepro", daemonize: true
  end
  
end
